### ISSUE TITLE
I want to make a friend with you

### ISSUE THREAD

**Issue by yuchonghua** [mogwai/typescript-webpack-serverless#1]
I want to make a friend with you, can I leave a mailbox for me, my email address is yuchonghua@163.com

**Comment by yuchonghua** [comment]
[Easycms](https://www.npmjs.com/package/easycms) This npm name can be transferred to me, my npm user account is yuchonghua, thank you very much

**Comment by mogwai** [comment]
I would be happy to. I'll try to do it this week

**Comment by yuchonghua** [comment]
Thank you very much for your support, because I want to develop a fast-starting cms, named easycms, and I look forward to your joining.
